name: Release Latest Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  branch-setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove README
        run: |
          rm -f README.md
          rm -rf .github
      
      - name: Set up Git
        run: |
          # bot name from secrets
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"
          git checkout --orphan latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-mac:
    runs-on: macos-latest
    needs: [branch-setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: latest-release

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create Virtual Environment
        run: |
          python -m venv py313-mac
          rm py313-mac/.gitignore
      
      - name: Install Dependencies
        run: |
          source py313-mac/bin/activate
          pip install -r requirements.txt
      
      - name: Debug Secret Values (TEMP)
        run: |
          echo "BOT_NAME: ${{ secrets.BOT_NAME }}"
          echo "BOT_EMAIL: ${{ secrets.BOT_EMAIL }}"
      
      - name: Set up Git
        run: |
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"
          git checkout latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-windows:
    runs-on: windows-latest
    needs: [branch-setup]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: latest-release

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create Virtual Environment
        run: |
          python -m venv py313-win
          del py313-win\.gitignore
      
      - name: Install Dependencies
        run: |
          .\py313-win\Scripts\activate
          pip install -r requirements.txt
      
      - name: Set up Git
        run: |
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"
          git checkout latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    needs: [branch-setup]
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: latest-release

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create Virtual Environment
        run: |
          python -m venv py313-linux
          rm py313-linux/.gitignore
      
      - name: Install Dependencies
        run: |
          source py313-linux/bin/activate
          pip install -r requirements.txt
      
      - name: Set up Git
        run: |
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"
          git checkout latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  release:
    runs-on: ubuntu-latest
    needs: [branch-setup, build-mac, build-windows, build-linux]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: latest-release

      - name: Remove README
        run: |
          rm -f requirements.txt

      - name: Version File
        run: |
          date +%s > version

      - name: Set up Git
        run: |
          git config user.name "${{ secrets.BOT_NAME }}"
          git config user.email "${{ secrets.BOT_EMAIL }}"
          git checkout latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

