name: Release Latest Build

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-mac:
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create Virtual Environment
        run: |
          python -m venv py313-mac
          rm py313-mac/.gitignore
      
      - name: Install Dependencies
        run: |
          source py313-mac/bin/activate
          pip install -r requirements.txt
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create Virtual Environment
        run: |
          python -m venv py313-win
          del py313-win\.gitignore
      
      - name: Install Dependencies
        run: |
          .\py313-win\Scripts\activate
          pip install -r requirements.txt
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-linux:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create Virtual Environment
        run: |
          python -m venv py313-linux
          rm py313-linux/.gitignore
      
      - name: Install Dependencies
        run: |
          source py313-linux/bin/activate
          pip install -r requirements.txt
      
      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Remove README
        run: |
          rm -f README.md
          rm -rf .github

      - name: Version File
        run: |
          date +%s > version

      - name: Set up Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git checkout --orphan latest-release

      - name: Commit and push changes
        run: |
          git add .
          git commit -m "Latest build $(date "+%Y-%m-%d %H:%M:%S")"
          git push -f origin latest-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

